apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: mysql-dados
spec:
  acessModes:
    -ReadWriteOnce
  resouces:
   requests: 
     storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: hueland/projeto-database:0.1
          args:
          - "--ignore-db-dir=lost+found"
          imagePullPolicy: Always
          name: mysql
          ports:
          - containerPort: 3306
            name: mysql

          volumeMounts:
            - name: mysql-dados
              mount-Path: /var/lib/mysql
        volumes:
          - name: mysql-dados
            persistentVolumeClaim:
              claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels: 
    app: php
  spec:
    replicas: 6
    selector:
      matchLabels:
        app: php
    template:
      metadata:
        labels:
          app: php
      spec:
        containers:
          - name: pqp
            image: hueland/projeto-backend:0.1
            imagePullPolicy: Always
            ports:
            - containerPort: 80          
